// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmkhkEh_CPkDY0lik93MYR_yII_2HKM1U',
    appId: '1:116368782292:web:3925c13259363af75f9c41',
    messagingSenderId: '116368782292',
    projectId: 'factory-management-8307e',
    authDomain: 'factory-management-8307e.firebaseapp.com',
    storageBucket: 'factory-management-8307e.firebasestorage.app',
    measurementId: 'G-NMRD9QQ1KE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNUb9BzgxqkUUPddI9bDdILL6le4vQ0U0',
    appId: '1:116368782292:android:1aaea384973ae33f5f9c41',
    messagingSenderId: '116368782292',
    projectId: 'factory-management-8307e',
    storageBucket: 'factory-management-8307e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFAonSdARnKwcp0nL0SupBWVmVFBIaUoE',
    appId: '1:116368782292:ios:a0a35f2b1dd805115f9c41',
    messagingSenderId: '116368782292',
    projectId: 'factory-management-8307e',
    storageBucket: 'factory-management-8307e.firebasestorage.app',
    iosBundleId: 'com.example.factoryManagement',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDmkhkEh_CPkDY0lik93MYR_yII_2HKM1U',
    appId: '1:116368782292:web:e0521221b9d70f7e5f9c41',
    messagingSenderId: '116368782292',
    projectId: 'factory-management-8307e',
    authDomain: 'factory-management-8307e.firebaseapp.com',
    storageBucket: 'factory-management-8307e.firebasestorage.app',
    measurementId: 'G-K4NQZP9G8J',
  );
}
